// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: filter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MedicalData   *MedicalData           `protobuf:"bytes,1,opt,name=medical_data,json=medicalData,proto3" json:"medical_data,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterRequest) Reset() {
	*x = FilterRequest{}
	mi := &file_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRequest) ProtoMessage() {}

func (x *FilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRequest.ProtoReflect.Descriptor instead.
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return file_filter_proto_rawDescGZIP(), []int{0}
}

func (x *FilterRequest) GetMedicalData() *MedicalData {
	if x != nil {
		return x.MedicalData
	}
	return nil
}

func (x *FilterRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type FilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilteredData  *MedicalData           `protobuf:"bytes,1,opt,name=filtered_data,json=filteredData,proto3" json:"filtered_data,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterResponse) Reset() {
	*x = FilterResponse{}
	mi := &file_filter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterResponse) ProtoMessage() {}

func (x *FilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterResponse.ProtoReflect.Descriptor instead.
func (*FilterResponse) Descriptor() ([]byte, []int) {
	return file_filter_proto_rawDescGZIP(), []int{1}
}

func (x *FilterResponse) GetFilteredData() *MedicalData {
	if x != nil {
		return x.FilteredData
	}
	return nil
}

func (x *FilterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FilterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FilterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_filter_proto protoreflect.FileDescriptor

const file_filter_proto_rawDesc = "" +
	"\n" +
	"\ffilter.proto\x12\x06filter\x1a\fcommon.proto\"f\n" +
	"\rFilterRequest\x126\n" +
	"\fmedical_data\x18\x01 \x01(\v2\x13.common.MedicalDataR\vmedicalData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x9b\x01\n" +
	"\x0eFilterResponse\x128\n" +
	"\rfiltered_data\x18\x01 \x01(\v2\x13.common.MedicalDataR\ffilteredData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2L\n" +
	"\rFilterService\x12;\n" +
	"\n" +
	"FilterData\x12\x15.filter.FilterRequest\x1a\x16.filter.FilterResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_filter_proto_rawDescOnce sync.Once
	file_filter_proto_rawDescData []byte
)

func file_filter_proto_rawDescGZIP() []byte {
	file_filter_proto_rawDescOnce.Do(func() {
		file_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filter_proto_rawDesc), len(file_filter_proto_rawDesc)))
	})
	return file_filter_proto_rawDescData
}

var file_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_filter_proto_goTypes = []any{
	(*FilterRequest)(nil),  // 0: filter.FilterRequest
	(*FilterResponse)(nil), // 1: filter.FilterResponse
	(*MedicalData)(nil),    // 2: common.MedicalData
}
var file_filter_proto_depIdxs = []int32{
	2, // 0: filter.FilterRequest.medical_data:type_name -> common.MedicalData
	2, // 1: filter.FilterResponse.filtered_data:type_name -> common.MedicalData
	0, // 2: filter.FilterService.FilterData:input_type -> filter.FilterRequest
	1, // 3: filter.FilterService.FilterData:output_type -> filter.FilterResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_filter_proto_init() }
func file_filter_proto_init() {
	if File_filter_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filter_proto_rawDesc), len(file_filter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filter_proto_goTypes,
		DependencyIndexes: file_filter_proto_depIdxs,
		MessageInfos:      file_filter_proto_msgTypes,
	}.Build()
	File_filter_proto = out.File
	file_filter_proto_goTypes = nil
	file_filter_proto_depIdxs = nil
}
