// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: ml.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MedicalData   *MedicalData           `protobuf:"bytes,1,opt,name=medical_data,json=medicalData,proto3" json:"medical_data,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_ml_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetMedicalData() *MedicalData {
	if x != nil {
		return x.MedicalData
	}
	return nil
}

func (x *PredictRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prediction    float64                `protobuf:"fixed64,1,opt,name=prediction,proto3" json:"prediction,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_ml_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetPrediction() float64 {
	if x != nil {
		return x.Prediction
	}
	return 0
}

func (x *PredictResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PredictResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PredictResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ml_proto protoreflect.FileDescriptor

const file_ml_proto_rawDesc = "" +
	"\n" +
	"\bml.proto\x12\x02ml\x1a\fcommon.proto\"g\n" +
	"\x0ePredictRequest\x126\n" +
	"\fmedical_data\x18\x01 \x01(\v2\x13.common.MedicalDataR\vmedicalData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x82\x01\n" +
	"\x0fPredictResponse\x12\x1e\n" +
	"\n" +
	"prediction\x18\x01 \x01(\x01R\n" +
	"prediction\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2?\n" +
	"\tMLService\x122\n" +
	"\aPredict\x12\x12.ml.PredictRequest\x1a\x13.ml.PredictResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_ml_proto_rawDescOnce sync.Once
	file_ml_proto_rawDescData []byte
)

func file_ml_proto_rawDescGZIP() []byte {
	file_ml_proto_rawDescOnce.Do(func() {
		file_ml_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ml_proto_rawDesc), len(file_ml_proto_rawDesc)))
	})
	return file_ml_proto_rawDescData
}

var file_ml_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ml_proto_goTypes = []any{
	(*PredictRequest)(nil),  // 0: ml.PredictRequest
	(*PredictResponse)(nil), // 1: ml.PredictResponse
	(*MedicalData)(nil),     // 2: common.MedicalData
}
var file_ml_proto_depIdxs = []int32{
	2, // 0: ml.PredictRequest.medical_data:type_name -> common.MedicalData
	0, // 1: ml.MLService.Predict:input_type -> ml.PredictRequest
	1, // 2: ml.MLService.Predict:output_type -> ml.PredictResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ml_proto_init() }
func file_ml_proto_init() {
	if File_ml_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ml_proto_rawDesc), len(file_ml_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ml_proto_goTypes,
		DependencyIndexes: file_ml_proto_depIdxs,
		MessageInfos:      file_ml_proto_msgTypes,
	}.Build()
	File_ml_proto = out.File
	file_ml_proto_goTypes = nil
	file_ml_proto_depIdxs = nil
}
